### ISSUE TITLE
Timeout support

### ISSUE THREAD

**Issue by OvermindDL1** [jmerriweather/exldap#1]
Would be quite nice to be able to set a timeout on all functions that support it, especially connection/logging in/search.

**Comment by jmerriweather** [comment]
yeah good idea, I'll see what I can do

**Comment by OvermindDL1** [comment]
Awesome, timeout was definitely needed, the ldap server here will sometimes return in milliseconds, other times 40 seconds, and since the records need to be retrieved fast or not at all...  :-)

**Comment by jmerriweather** [comment]
closed by #2
