### ISSUE TITLE
Settings could be nil

### ISSUE THREAD

**Issue by wstucco** [jmerriweather/exldap#12]
In line [238 of `exldap.ex`](https://github.com/jmerriweather/exldap/blob/3a3c405ca138f5554d4750bb8baab20bc2b99fc4/lib/exldap.ex#L238) `settings` could be `nil` and the subsequent `Keyword.get` could fail

A super quick & dirt workaround is to always set `:exldap` config in your app

```elixir
config :exldap, settings: []
```

**Comment by jmerriweather** [comment]
This issue should be fixed in 0.6.3
