### ISSUE TITLE
Verify credentials using field other than CN

### ISSUE THREAD

**Issue by Mbuckley0** [jmerriweather/exldap#3]
Is it possible to verify the credentials of a ldap user using something other than the CN such as uid or samaccountname?

**Comment by jmerriweather** [comment]
You could lookup the user using uid or samaccountname with the following:
```elixir
{:ok, search_result} = Exldap.search_field(connection, "sAMAccountName", username)
```
Then grab the DN from the results and pass that to the verify_credentials function
```elixir
{:ok, first_result} = search_result |> Enum.fetch(0)
dn = Exldap.search_attributes(first_result, "distinguishedName")
Exldap.verify_credentials(connection, dn, password)
```

**Comment by Mbuckley0** [comment]
Thanks that works well. Is it possible to do a search without connecting using user credentials first? i.e. Using Exldap.open and then doing a search from the resulting connection of that?

**Comment by jmerriweather** [comment]
No worries. Unfortunately that's not possible as LDAP won't allow you to query it until it knows you have permissions to do so. What I normally do is create a LDAP user account for the application and set that in the config.secret.exs

**Comment by Mbuckley0** [comment]
I thought that might be the case. Thanks for your help.
