### ISSUE TITLE
Parameters with accents have unexpected outcome

### ISSUE THREAD

**Issue by cbioley** [jmerriweather/exldap#5]
When the user dn and/or the password parameter passed to `Exldap.verify_credentials` contains an accent, the result is unexpected since it does return an error (invalid credentials) while it should not.

Any advice on how to overcome (and understand) this issue?

Thank you ;)

**Comment by jmerriweather** [comment]
Could you try the following and let me know if it does the same thing
```elixir
#replace Exldap.verify_credentials(connection, user_dn, password) with:
:eldap.simple_bind(connection, user_dn, password)
```

**Comment by cliengme** [comment]
It seems to work on my side with your solution.

**Comment by cbioley** [comment]
@jmerriweather Thank you. It does indeed fix the issue 👏

@cliengme Thanks mate. Now I feel really old ;)
