### ISSUE TITLE
verify_credentials/3 when given empty string password is :ok

### ISSUE THREAD

**Issue by elliotthilaire** [jmerriweather/exldap#6]
Thanks for making this.

I'm getting some unexpected behaviour with `Exldap.verify_credentials/3`.
When I pass an empty string as the password the response is `:ok` when I expected this to be `{:error, :invalidCredentials}`

Is this expected behaviour or a bug?

Valid user_dn and password work as expected:
```
{:ok, connection} = Exldap.open()
valid_user_dn = "CN=Elliott,OU=Users,DC=example,DC=com"
Exldap.verify_credentials(connection, valid_user_dn, "MyActualPassword")
=> :ok
``` 

Valid user_dn and incorrect password work as expected:
```
{:ok, connection} = Exldap.open()
valid_user_dn = "CN=Elliott,OU=Users,DC=example,DC=com"
Exldap.verify_credentials(connection, valid_user_dn, "IncorrectPassword")
=> {:error, :invalidCredentials}
``` 

Valid user_dn and incorrect empty string password return :ok
```
{:ok, connection} = Exldap.open()
valid_user_dn = "CN=Elliott,OU=Users,DC=example,DC=com"
Exldap.verify_credentials(connection, valid_user_dn, "")
=> :ok
```

Invalid user_dn and incorrect empty string password return :ok
```
{:ok, connection} = Exldap.open()
Exldap.verify_credentials(connection, "not_a_real_dn", "")
=> :ok
```

**Comment by jmerriweather** [comment]
This does appears to be a bug, ldap allows an unauthenticated bind to be successful when the password is blank. I should be checking for an empty string in the password field: https://tools.ietf.org/html/rfc4513#section-6.3.1

Fix incoming
